#no cache during dev
[globalString = ENV:HTTP_HOST=valid-typo3.vd.ch/]
  page.config.no_cache = 1
[GLOBAL]





# Page & Templavoilà
page = PAGE
page {

  # Templavoilà
  10 = USER
  10.userFunc = tx_templavoila_pi1->main_page
  10.disableExplosivePreview = 1

  # Set a bg color on body tag
  bodyTag = <body bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-webkit-text-size-adjust: none;height: 100%;width: 100%;">

  # meta tags
  meta {

    # viewport
    viewport = width=­dev­ice­-width

  }

  # CSS
  includeCSS {
    email = fileadmin/templates/extensions/direct_mail/hero-email-template/stylesheets/email.css
  }

  includeJSFooterlibs {
    jquery = https://code.jquery.com/jquery-1.11.1.min.js
    jquery.external = 1
  }

  jsInline {
    10 = TEXT
    10.value = $('.body-wrap img').removeAttr('width').removeAttr('height');
  }

}






# Config
config {

  # Doctype
  doctype = xhtml_trans

  # XHTML cleaning
  xhtml_cleaning = all

  # set base URL
  baseURL = {$lib.baseUrl}

  # enable realurl
  tx_realurl_enable = 1

  # Protect email from SPAM
  spamProtectEmailAddresses = 1

  # Default JavaScript in the header will be removed.
  removeDefaultJS = 1

  # Remove CSS generated by _CSS_DEFAULT_STYLE
  removeDefaultCss = 1

}





# Logo
lib.logo {
  department = TEXT
  department.value = {$lib.department}

  service = TEXT
  service.value = {$lib.service}
}





# Banner text
lib.bannertext = TEXT
lib.bannertext {
  value = {$lib.newsletter.bannertext}
}




# Page title
lib.title = COA
lib.title {
    10 = TEXT
    10.wrap = <h1>|</h1>
    10.insertData = 1
    10.value = {page:title // page:subtitle}
}





##
# Footer
##

# Footer left header
lib.footer.left.header= RECORDS
lib.footer.left.header {
  source = {$lib.newsletter.footer.left}
  tables = tt_content
  conf.tt_content = COA
  conf.tt_content {
    1 = TEXT
    1.field = header
  }
}

# Footer left content
lib.footer.left.content < lib.footer.left.header
lib.footer.left.content.conf.tt_content.1.field = bodytext
lib.footer.left.content.conf.tt_content.1.parseFunc = < lib.parseFunc_RTE

# Footer right header
lib.footer.right.header < lib.footer.left.header
lib.footer.right.header.source = {$lib.newsletter.footer.right}

# Footer right content
lib.footer.right.content < lib.footer.left.content
lib.footer.right.content.source = {$lib.newsletter.footer.right}





# Liens de pied de page
lib.footer.links = COA
lib.footer.links {

  # Gestion abonnement
  10 = TEXT
  10 {
    value = {$lib.baseUrl}?id={$lib.idToUnsubscribe}&cmd=edit&aC=###SYS_AUTHCODE###&rU=###USER_uid###
    wrap = <a href="|" title="Lien vers l'interface d'administration de l'abonnement a la newsletter" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;color: #c60;">G&eacute;rer mon abonnement</a>
  }

  # Visualiser dans le navigateur
  20 = TEXT
  20 {
    value = Visualiser dans le navigateur
    typolink {
      parameter.data = TSFE:id
      title = Lien vers la newsletter
      ATagParams = style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;color: #c60;"
    }
    noTrimWrap = | &#124; ||
  }

}
